# Generated by Django 3.2.4 on 2021-09-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('uri_name', models.SlugField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='categories')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('date_from', models.DateField()),
                ('time_from', models.TimeField()),
                ('date_to', models.DateField()),
                ('time_to', models.TimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recipe', models.TextField(blank=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='menu_items')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category')),
                ('offer', models.ManyToManyField(blank=True, to='menus.Offer')),
                ('restruant', models.ManyToManyField(blank=True, to='restaurants.Restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menuitem')),
            ],
        ),
    ]
