# Generated by Django 3.2.5 on 2021-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
