# Generated by Django 3.2.5 on 2021-08-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menuitem_is_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_added',
        ),
    ]
