# Generated by Django 3.2.5 on 2021-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_menuitem_is_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('time_from', models.TimeField()),
                ('date_to', models.DateField()),
                ('time_to', models.TimeField()),
            ],
        ),
    ]
