# Generated by Django 3.2.5 on 2021-08-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menuitem_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='big billion offer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
            preserve_default=False,
        ),
    ]
