# Generated by Django 3.2.5 on 2021-08-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20210807_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
