# Generated by Django 3.2.5 on 2021-08-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20210807_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='discount',
        ),
    ]
