# Generated by Django 3.2.4 on 2021-08-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_rename_price_offer_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
    ]
