# Generated by Django 3.2.4 on 2021-08-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
