# Generated by Django 3.2.4 on 2021-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210829_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='actual_delivery_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='estimated_delivery_time',
            field=models.TimeField(blank=True),
        ),
    ]
