# Generated by Django 3.2.4 on 2021-08-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210829_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='restraunt',
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='estimated_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
