# Generated by Django 3.2.4 on 2021-08-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210829_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='actual_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
