# Generated by Django 3.2.4 on 2021-08-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_placedorder_actual_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='email',
            field=models.CharField(default='atifshafi63@gmail.com', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedorder',
            name='mob_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
