# Generated by Django 3.2.5 on 2021-08-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0005_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
            preserve_default=False,
        ),
    ]
