# Generated by Django 3.2.4 on 2021-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210829_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='item_name',
            field=models.CharField(default='Fresh Veggie Bagel Sandwic', max_length=255),
            preserve_default=False,
        ),
    ]
