# Generated by Django 3.2.5 on 2021-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_placedorder_is_delivered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InOrder',
        ),
    ]
