# Generated by Django 3.2.5 on 2021-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_inorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='large', max_length=25),
            preserve_default=False,
        ),
    ]
