# Generated by Django 3.2.5 on 2021-08-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_offer'),
        ('orders', '0009_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.ManyToManyField(to='menus.Offer'),
        ),
    ]
