# Generated by Django 3.2.5 on 2021-08-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cartitem_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='offer',
        ),
    ]
