# Generated by Django 3.2.5 on 2021-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_cartitem_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
