# Generated by Django 3.2.5 on 2021-08-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210812_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='food_ready_time',
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordereditem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.placedorder')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ordered_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordereditems'),
        ),
    ]
