# Generated by Django 3.2.5 on 2021-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210812_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='item_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='size',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
