# Generated by Django 3.2.5 on 2021-08-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_offer_options'),
        ('orders', '0015_auto_20210812_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='item_name',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menuitem'),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='building',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='city',
            field=models.CharField(default='lalbazar', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedorder',
            name='zip_code',
            field=models.CharField(default=23444, max_length=25),
            preserve_default=False,
        ),
    ]
