# Generated by Django 3.2.4 on 2021-08-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_cart_session_id'),
        ('orders', '0015_auto_20210812_1505'),
    ]

    operations = [
    ]
