# Generated by Django 3.2.5 on 2021-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210817_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
