# Generated by Django 3.2.4 on 2021-08-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_merge_20210828_1519'),
        ('orders', '0017_alter_placedorder_order_time'),
    ]

    operations = [
    ]
